#!/bin/bash
set -eu

RETH_DIR=/home/luffy/nodes/base
IPC_PATH=$RETH_DIR/data/reth.ipc
RETH_DATA_DIR=$RETH_DIR/data
RETH_LOG_DIR=$RETH_DIR/logs
RETH_CONFIG_FILE=$RETH_DIR/config.toml
BINARY=$RETH_DIR/base-reth-node
RPC_PORT="${RPC_PORT:-8645}"
WS_PORT="${WS_PORT:-8646}"
AUTHRPC_PORT="${AUTHRPC_PORT:-8552}"
METRICS_PORT="${METRICS_PORT:-6060}"
DISCOVERY_PORT="${DISCOVERY_PORT:-30304}"
P2P_PORT="${P2P_PORT:-30304}"
ADDITIONAL_ARGS=""

if [[ -z "${RETH_CHAIN:-}" ]]; then
    echo "expected RETH_CHAIN to be set" 1>&2
    exit 1
fi

# Enable Flashblocks support if websocket URL is provided
if [[ -n "${RETH_FB_WEBSOCKET_URL:-}" ]]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --websocket-url=$RETH_FB_WEBSOCKET_URL"
    echo "Enabling Flashblocks support with endpoint: $RETH_FB_WEBSOCKET_URL"
else
    echo "Running in vanilla node mode (no Flashblocks URL provided)"
fi

# Add pruning for base
if [[ "${RETH_PRUNING_ARGS+x}" = x ]]; then
    echo "Adding pruning arguments: $RETH_PRUNING_ARGS"
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS $RETH_PRUNING_ARGS"
fi

mkdir -p "$RETH_DATA_DIR"
echo "Starting reth with additional args: $ADDITIONAL_ARGS"
echo "$OP_NODE_L2_ENGINE_AUTH_RAW" > "$OP_NODE_L2_ENGINE_AUTH"

exec "$BINARY" node \
  -vvv \
  --full \
  --config="$RETH_CONFIG_FILE" \
  --datadir="$RETH_DATA_DIR" \
  --log.file.directory="$RETH_LOG_DIR" \
  --log.file.name="reth.log" \
  --ws \
  --ws.origins="*" \
  --ws.addr=127.0.0.1 \
  --ws.port="$WS_PORT" \
  --ws.api=web3,debug,eth,net,txpool \
  --http \
  --http.corsdomain="*" \
  --http.addr=127.0.0.1 \
  --http.port="$RPC_PORT" \
  --http.api=web3,debug,eth,net,txpool,miner \
  --ipcpath="$IPC_PATH" \
  --authrpc.addr=127.0.0.1 \
  --authrpc.port="$AUTHRPC_PORT" \
  --authrpc.jwtsecret="$OP_NODE_L2_ENGINE_AUTH" \
  --max-outbound-peers=100 \
  --chain "$RETH_CHAIN" \
  --rollup.sequencer-http="$RETH_SEQUENCER_HTTP" \
  --rollup.disable-tx-pool-gossip \
  --discovery.port="$DISCOVERY_PORT" \
  --port="$P2P_PORT" \
  $ADDITIONAL_ARGS > /dev/null 2>&1
